spring:
  application:
    name: CalendarAPI
  datasource:
    url: jdbc:postgresql://localhost:5434/calendar_db
    password: calendar_password
    username: calendar_user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: calendar_user
    password: calendar_password
    url: jdbc:postgresql://localhost:5434/calendar_db
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: calendar-client
            client-secret: BsJGa8vBJylJCpgohSFLBSQsEgo3SgL4
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/calendar-app

server:
  port: 8081
